### ISSUE TITLE
'LeadViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.

### ISSUE THREAD

**Issue by 362466** [bradtraversy/lead_manager_react_django#1]
'LeadViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method on below line in api.py file
 queryset : Lead.objects.all()

I am following Part1 video, while running server, I am getting above mentioned error. Any work around or any piece of code, which I have to double cross. I have already checked the code multiple time, every time seems to be dot to dot.

**Comment by bradtraversy** [comment]
It should be an "=". Like this...

queryset = Lead.objects.all()

**Comment by 362466** [comment]
> It should be an "=". Like this...
> 
> queryset = Lead.objects.all()

How come I missed it, wasted 3 hours on this. Great catch. Thanks for quick response.

**Comment by bradtraversy** [comment]
No problem :)
