### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by sajaddadras** [bradtraversy/lead_manager_react_django#15]
Hi there Brad, Thank you for your great tutorial, I get an error when I run the "npm run build" command.

**Error:**

webpack is watching the files…

**Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.**

Hash: 1a8ae2f3f9b1fc0393e9
Version: webpack 4.39.3
Time: 49ms
Built at: 09/07/2019 11:51:57 PM

ERROR in Entry module not found: **Error: Can't resolve 'babel-loader' in '/Users/apple/My_project/NewDJ'**

**Comment by alphaTdeeraj** [comment]
@sajaddadras, do you have build script in your package.json file

**Comment by prime7** [comment]
@sajaddadras Change the paths in dev and build according to your setup.

**Comment by Shobhit2806** [comment]
Hi @sajaddadras, I am facing the same issue. How do you resolve this issue?
