### ISSUE TITLE
Why it doesn't have a requirements.txt

### ISSUE THREAD

**Issue by miraccan00** [bradtraversy/lead_manager_react_django#65]
I have tried couple of times to run Django side but I got error. Can you add a requirements.txt

**Comment by PoSihDun** [comment]
arrow==1.2.1
asgiref==3.4.1
cffi==1.15.0
cryptography==36.0.0
Django==3.2.10 ---- django4 is not compatible with knox atm
django-location-field==2.1.0
django-phonenumber-field==6.0.0
django-rest-knox==4.1.0
djangorestframework==3.12.4
phonenumbers==8.12.39
psycopg2==2.9.2
pycparser==2.21
python-dateutil==2.8.2
pytz==2021.3
six==1.16.0
sqlparse==0.4.2
tzdata==2021.5

**Comment by miraccan00** [comment]
Thank you for your feedback, we can add requirements.txt to this repository
